name: data4impact
description: Data 4 Impact
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  audioplayers: ^6.5.1
  awesome_bottom_bar: ^1.2.4
  bloc: ^8.1.4
  dio: ^5.9.0
  equatable: ^2.0.7
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_web_auth_2: ^4.1.0
  geolocator: ^14.0.2
  google_fonts: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.0
  hugeicons: ^0.0.11
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.6.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  record: ^6.1.1
  sign_in_button: ^4.0.1
  toastification: ^3.0.3
  url_launcher: ^6.3.2
  skeletonizer: ^2.1.0+1
  flutter_launcher_icons: ^0.14.4
  csv:
  share_plus:
  device_info_plus: ^9.0.0
  open_file:

dev_dependencies:
  hive_generator: ^2.0.1
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  build_runner:

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/image/